version: '3.4'
services:
  db:
    image: postgres:latest
    container_name: ${MYSQL_HOST}
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'conceitoexato'
    ports:
      - '5432:5432'
    expose:
      - '5432'

  # app:
  #   build: .
  #   image: tic/backend
  #   container_name: winners
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
