version: '3.4'
services:
  db:
    image: mysql:5.7
    container_name: ${MYSQL_HOST}
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'

  # app:
  #   build: .
  #   image: tic/backend
  #   container_name: winners
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:8080
